# ckan-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Size as per your requirement
