apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckan-helm.solr.fullname" . }}
  labels:
{{ include "ckan-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.solr.service.type }}
  ports:
    - port: {{ .Values.solr.service.port }}
      targetPort: solr
      protocol: TCP
      name: solr
  selector:
    app: {{ include "ckan-helm.solr.fullname" . }}
